### ISSUE TITLE
Texts are abbreviated / overlapping other content + can't resize the window

### ISSUE THREAD

**Issue by rmeissn** [guitarmarx/DockerConverter#1]
Some texts of the application are abbreviated/overlap other content due to a too small window + I can't resize the window. This is a little annoying. See the attached Screenshots.

![screenshot 1](https://user-images.githubusercontent.com/855967/30700224-47529cbe-9ee7-11e7-8814-0fce145f97ab.png)

![screenshot 2](https://user-images.githubusercontent.com/855967/30700226-4a00cfd0-9ee7-11e7-9c30-569e02f9facd.png)

**Comment by guitarmarx** [comment]
Updated UI and changed layout. Most of the elements are now resizable and won't abbreviated the content. I will introduce a new graphical interface in the future to get rid of these ui bugs.
