### ISSUE TITLE
Paths containing whitespaces are only partially supported

### ISSUE THREAD

**Issue by rmeissn** [guitarmarx/DockerConverter#2]
As the applications asks me to select a path to use as a temporary and export directory, I created "DockerConverter test" as a folder. After pulling the image, the application showed me an error popup, but still displays content of the image + everything else. This is annoying as I don't know if something's wrong or not and whether I received all information that I would have received without the error popup. After adding an underscore to the path, it worked as expected.

Command line logs printed: 
```
docker save -o /home/<USER>/Downloads/DockerConverter test/wonderfall-nextcloud-12.0.tar wonderfall/nextcloud:12.0
Error response from daemon: No such image: test/wonderfall-nextcloud-12.0.tar
```

**Comment by guitarmarx** [comment]
Image extraction process got updated, whitespaces are now supported.
