### ISSUE TITLE
Mixed languages in the UI (English and German)

### ISSUE THREAD

**Issue by rmeissn** [guitarmarx/DockerConverter#3]
Texts in the UI of the application are sometimes written in German (e.g. "Exportpfad" or "Typ") and are sometimes written in English (e.g. "Process", "Convert"). Please decide for one language or introduce multilingualism.

**Comment by guitarmarx** [comment]
UI elements got updated, mixed languages are now removed. Multilangualism might be implemented in the future. I will create a story in the backlog for that.
