### ISSUE TITLE
Malicious line in reconstructed Dockerfile "//nodeApp in /nodeApp""

### ISSUE THREAD

**Issue by rmeissn** [guitarmarx/DockerConverter#7]
I've processed the image "slidewiki/platform" and reconstructed the Dockerfile. There is a line in it, that holds no Docker related command and `docker build ./` refuses to execute because of this line.

```
....
MAINTAINER XYZ
WORKDIR /nodeApp
//nodeApp in /nodeApp
RUN ./make_version.sh
....
```

**Comment by guitarmarx** [comment]
Bug is fixed, this line was caused by missing COPY command in the transformation. Note, the docker build command to create a new image with the exported Dockerfile is still unsupported, because of the missing FROM clause in the Docker History.
